on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        gnat_version: [^11]
        gprbuild_version: [^21]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: ada-actions/toolchain@ce2020
      - uses: alire-project/setup-alire@v1
        with:
          branch: "gnatcov"
          toolchain: gprbuild${{ matrix.gprbuild_version }} gnat_native${{ matrix.gnat_version }} --disable-assistant

      - run: alr build

      - run: alr coverage --instrument

      - run: alr build --cov-instr

      - run: ./bin/gnatcov_poc

      - run: alr coverage --report *.srctrace

      - run: cat gnatcov_out/gnatcov_poc.adb.xcov

      - uses: alire-project/gnatcov-to-codecovio-action@main
        with:
          fail_ci_if_error: true
          verbose: true
