on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        gnat_version: [^11]
        gprbuild_version: [^21]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: ada-actions/toolchain@ce2020
      - uses: alire-project/setup-alire@v1
        with:
          branch: "master"
          toolchain: gprbuild${{ matrix.gprbuild_version }} gnat_native${{ matrix.gnat_version }} --disable-assistant

      - run: alr build

      - run: alr config --set --global alias.instrument "exec -- gnatcov instrument -P gnatcov_poc.gpr"
      - run: alr config --set --global alias.build_cov "build -- --src-subdirs=gnatcov-instr --implicit-with=gnatcov_rts_full"
      - run: alr config --set --global alias.coverage "exec -- gnatcov coverage -P gnatcov_poc.gpr"

      - run: alr instrument

      - run: alr build_cov

      - run: ./bin/gnatcov_poc

      - run: alr coverage gnatcov_poc.srctrace

      - run: cat gnatcov_out/gnatcov_poc.adb.xcov

      - uses: alire-project/gnatcov-to-codecovio-action@main
        with:
          fail_ci_if_error: true
          verbose: true
